"""empty message

Revision ID: 754e22c117c1
Revises: 8f8e65bff0f6
Create Date: 2020-09-11 17:33:49.406662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '754e22c117c1'
down_revision = '8f8e65bff0f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role', sa.Column('restaurant_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'role', 'restaurant', ['restaurant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'role', type_='foreignkey')
    op.drop_column('role', 'restaurant_id')
    # ### end Alembic commands ###
