"""empty message

Revision ID: 8f8e65bff0f6
Revises: 450af8f2f02f
Create Date: 2020-09-11 16:22:37.095583

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8f8e65bff0f6'
down_revision = '450af8f2f02f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dish', 'restaurant_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dish', 'restaurant_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
