"""empty message

Revision ID: cd896611199a
Revises: d9f6fe1b871e
Create Date: 2020-09-30 18:19:45.971479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd896611199a'
down_revision = 'd9f6fe1b871e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('city',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('latitude', sa.String(length=120), nullable=False),
    sa.Column('longitude', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('latitude'),
    sa.UniqueConstraint('longitude')
    )
    op.add_column('restaurant', sa.Column('city', sa.String(length=120), nullable=False))
    op.add_column('restaurant', sa.Column('city_id', sa.Integer(), nullable=True))
    op.add_column('restaurant', sa.Column('country', sa.String(length=120), nullable=False))
    op.add_column('restaurant', sa.Column('latitude', sa.String(length=120), nullable=False))
    op.add_column('restaurant', sa.Column('longitude', sa.String(length=120), nullable=False))
    op.create_unique_constraint(None, 'restaurant', ['city'])
    op.create_unique_constraint(None, 'restaurant', ['longitude'])
    op.create_unique_constraint(None, 'restaurant', ['country'])
    op.create_unique_constraint(None, 'restaurant', ['latitude'])
    op.create_foreign_key(None, 'restaurant', 'city', ['city_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'restaurant', type_='foreignkey')
    op.drop_constraint(None, 'restaurant', type_='unique')
    op.drop_constraint(None, 'restaurant', type_='unique')
    op.drop_constraint(None, 'restaurant', type_='unique')
    op.drop_constraint(None, 'restaurant', type_='unique')
    op.drop_column('restaurant', 'longitude')
    op.drop_column('restaurant', 'latitude')
    op.drop_column('restaurant', 'country')
    op.drop_column('restaurant', 'city_id')
    op.drop_column('restaurant', 'city')
    op.drop_table('city')
    # ### end Alembic commands ###
