"""empty message

Revision ID: e80923fee4a8
Revises: cd896611199a
Create Date: 2020-09-30 18:22:18.039979

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e80923fee4a8'
down_revision = 'cd896611199a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('city', table_name='restaurant')
    op.drop_index('country', table_name='restaurant')
    op.drop_column('restaurant', 'country')
    op.drop_column('restaurant', 'city')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurant', sa.Column('city', mysql.VARCHAR(length=120), nullable=False))
    op.add_column('restaurant', sa.Column('country', mysql.VARCHAR(length=120), nullable=False))
    op.create_index('country', 'restaurant', ['country'], unique=True)
    op.create_index('city', 'restaurant', ['city'], unique=True)
    # ### end Alembic commands ###
